doctrine:
    dbal:
        driver: 'pdo_mysql'
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '%database_server_version%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            FOSUserBundle:    ~
            SonataUserBundle: ~
        dql:
            string_functions:
                concat_ws: DoctrineExtensions\Query\Mysql\ConcatWs
            datetime_functions:
                year:        DoctrineExtensions\Query\Mysql\Year
                month:       DoctrineExtensions\Query\Mysql\Month
                date_format: DoctrineExtensions\Query\Mysql\DateFormat
