doctrine:
    dbal:
        driver:  'pdo_mysql'
        url:     '%env(resolve:DATABASE_URL)%'
        charset: 'utf8'
        types:
            json: Doctrine\DBAL\Types\JsonType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy:             doctrine.orm.naming_strategy.underscore
        auto_mapping:                true
        mappings:
            App:
                is_bundle: false
                type:      annotation
                alias:     App
                dir:       '%kernel.project_dir%/src/Entity'
                prefix:    'App\Entity'
        dql:
            string_functions:
                concat_ws:   DoctrineExtensions\Query\Mysql\ConcatWs
            datetime_functions:
                day:         DoctrineExtensions\Query\Mysql\Day
                month:       DoctrineExtensions\Query\Mysql\Month
                year:        DoctrineExtensions\Query\Mysql\Year
                date:        DoctrineExtensions\Query\Mysql\Date
                date_format: DoctrineExtensions\Query\Mysql\DateFormat
