doctrine:
    dbal:
        driver:  'pdo_mysql'
        url:     '%env(resolve:DATABASE_URL)%'
        charset: 'utf8'
        types:
            json: Doctrine\DBAL\Types\JsonType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy:             doctrine.orm.naming_strategy.underscore
        auto_mapping:                true
        enable_lazy_ghost_objects:   true
        mappings:
            App:
                is_bundle: false
                type:      annotation
                alias:     App
                dir:       '%kernel.project_dir%/src/Entity'
                prefix:    'App\Entity'
        dql:
            string_functions:
                concat_ws:   DoctrineExtensions\Query\Mysql\ConcatWs
            datetime_functions:
                day:         DoctrineExtensions\Query\Mysql\Day
                month:       DoctrineExtensions\Query\Mysql\Month
                year:        DoctrineExtensions\Query\Mysql\Year
                date:        DoctrineExtensions\Query\Mysql\Date
                date_format: DoctrineExtensions\Query\Mysql\DateFormat
        filters:
            operator_absence_filter: App\Doctrine\Filter\OperatorAbsencesFilter

when@test:
    doctrine:
        dbal:
            driver: 'pdo_sqlite'
        orm:
            dql:
                string_functions:
                    concat_ws: DoctrineExtensions\Query\Sqlite\ConcatWs
                datetime_functions:
                    day: DoctrineExtensions\Query\Sqlite\Day
                    month: DoctrineExtensions\Query\Sqlite\Month
                    year: DoctrineExtensions\Query\Sqlite\Year
                    date: DoctrineExtensions\Query\Sqlite\Date
                    date_format: DoctrineExtensions\Query\Sqlite\DateFormat

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
