fos_ck_editor:
    autoload:  false
    async:     true
    inline:    false
    base_path: 'build/ckeditor'
    js_path:   'build/ckeditor/ckeditor.js'
    configs:
        my_config:
            toolbar: standard
            height: 400
