fos_js_routing:
    routes_to_expose:
        - 'admin_app_partner_partner_getJsonPartnerById'
        - 'admin_app_partner_partner_getPartnerContactsById'
        - 'admin_app_partner_partner_getJsonDeliveryNotesById'
        - 'admin_app_sale_saletariff_getJsonSaleTariffById'
