fos_js_routing:
    routes_to_expose:
        - 'admin_app_partner_partner_getJsonPartnerById'
        - 'admin_app_partner_partner_getPartnerContactsById'
        - 'admin_app_partner_partner_getJsonBuildingSitesById'
        - 'admin_app_partner_partner_getJsonOrdersById'
        - 'admin_app_partner_partner_getJsonProjectsById'
        - 'admin_app_partner_partner_getJsonDeliveryNotesById'
        - 'admin_app_sale_saletariff_getJsonSaleTariffById'
        - 'admin_app_sale_saleservicetariff_getJsonSaleTariffById'
        - 'admin_app_operator_operatorworkregister_getJsonOperatorWorkRegistersByDataAndOperatorId'
        - 'admin_app_sale_saleinvoice_getJsonNextInvoiceNumberForSeriesIdAndInvoice'
        - 'admin_app_operator_operatorworkregisterheader_getJsonOperatorWorkRegisterTotalsByHourType'
        - 'admin_app_sale_saleinvoice_getJsonAvailableInvoiceNumbersForSeries'
        - 'admin_app_enterprise_enterpriseholidays_checkIfDayIsEnterpriseHoliday'
        - 'admin_app_partner_client_checkIfCifNifIsUsedInAnotherPartners'
        - 'admin_app_operator_operatorworkregister_customChangeDeliveryNote'
