security:
    enable_authenticator_manager: true
    role_hierarchy:
        ROLE_SONATA_CMS:
            - ROLE_APP_ADMIN_SERVICE_ALL
            - ROLE_APP_ADMIN_WORK_ALL
            - ROLE_APP_ADMIN_WORK_IMAGE_ALL
            - ROLE_APP_ADMIN_COMPLEMENT_ALL
            - ROLE_APP_ADMIN_CONTACT_MESSAGE_ALL
        ROLE_SONATA_MANAGER:
            - ROLE_APP_ADMIN_PROVINCE_ALL
            - ROLE_APP_ADMIN_CITY_ALL
            - ROLE_APP_ADMIN_ENTERPRISE_LIST
            - ROLE_APP_ADMIN_ENTERPRISE_VIEW
            - ROLE_APP_ADMIN_ENTERPRISE_EDIT
            - ROLE_APP_ADMIN_ENTERPRISE_EXPORT
            - ROLE_APP_ADMIN_OPERATOR_ALL
            - ROLE_APP_ADMIN_OPERATOR_DIGITAL_TACHOGRAPH_ALL
            - ROLE_APP_ADMIN_OPERATOR_CHECKING_ALL
            - ROLE_APP_ADMIN_OPERATOR_ABSENCE_ALL
            - ROLE_APP_ADMIN_OPERATOR_VARIOUS_AMOUNT_ALL
            - ROLE_APP_ADMIN_OPERATOR_WORK_REGISTER_HEADER_ALL
#            - ROLE_APP_ADMIN_OPERATOR_WORK_REGISTER_ALL
            - ROLE_APP_ADMIN_OPERATOR_WORK_REGISTER_EDIT
            - ROLE_APP_ADMIN_OPERATOR_WORK_REGISTER_DELETE
            - ROLE_APP_ADMIN_VEHICLE_ALL
            - ROLE_APP_ADMIN_VEHICLE_CATEGORY_ALL
            - ROLE_APP_ADMIN_VEHICLE_CHECKING_ALL
            - ROLE_APP_ADMIN_VEHICLE_DIGITAL_TACHOGRAPH_ALL
            - ROLE_APP_ADMIN_VEHICLE_CONSUMPTION_ALL
            - ROLE_APP_ADMIN_VEHICLE_SPECIAL_PERMIT_ALL
            - ROLE_APP_ADMIN_VEHICLE_MAINTENANCE_ALL
            - ROLE_APP_ADMIN_VEHICLE_MAINTENANCE_TASK_ALL
            - ROLE_APP_ADMIN_VEHICLE_FUEL_ALL
            - ROLE_APP_ADMIN_PARTNER_ALL
            - ROLE_APP_ADMIN_CLIENT_PARTNER_ALL
            - ROLE_APP_ADMIN_PARTNER_ORDER_ALL
            - ROLE_APP_ADMIN_PARTNER_PROJECT_ALL
            - ROLE_APP_ADMIN_PARTNER_BUILDING_SITE_ALL
            - ROLE_APP_ADMIN_PARTNER_CONTACT_ALL
            - ROLE_APP_ADMIN_PARTNER_UNABLE_DAYS_ALL
            - ROLE_APP_ADMIN_PARTNER_DELIVERY_ADDRESS_ALL
            - ROLE_APP_ADMIN_SALE_TARIFF_ALL
            - ROLE_APP_ADMIN_SALE_REQUEST_ALL
            - ROLE_APP_ADMIN_SALE_DELIVERY_NOTE_ALL
            - ROLE_APP_ADMIN_SALE_DELIVERY_NOTE_LINE_ALL
            - ROLE_APP_ADMIN_SALE_INVOICE_ALL
#            - ROLE_APP_ADMIN_SALE_REQUEST_HAS_DELIVERY_NOTE_ALL
            - ROLE_APP_ADMIN_SALE_SERVICE_TARIFF_ALL
            - ROLE_APP_ADMIN_ACTIVITY_LINE_ALL
            - ROLE_APP_ADMIN_SALE_INVOICE_SERIES_ALL
        ROLE_SONATA_MANAGER_ADMIN:
            - ROLE_APP_ADMIN_VEHICLE_CHECKING_TYPE_ALL
            - ROLE_APP_ADMIN_OPERATOR_CHECKING_TYPE_ALL
            - ROLE_APP_ADMIN_OPERATOR_ABSENCE_TYPE_ALL
            - ROLE_APP_ADMIN_ENTERPRISE_CREATE
            - ROLE_APP_ADMIN_ENTERPRISE_DELETE
            - ROLE_APP_ADMIN_ENTERPRISE_GROUP_BOUNTY_ALL
            - ROLE_APP_ADMIN_ENTERPRISE_TRANSFER_ACCOUNT_ALL
            - ROLE_APP_ADMIN_ENTERPRISE_HOLLIDAYS_ALL
            - ROLE_APP_ADMIN_ACTIVITY_LINE_ALL
            - ROLE_APP_ADMIN_COLLECTION_DOCUMENT_TYPE_ALL
            - ROLE_APP_ADMIN_TIME_RANGE_LIST
            - ROLE_APP_ADMIN_USER_ALL
            - ROLE_APP_ADMIN_PARTNER_CLASS_ALL
            - ROLE_APP_ADMIN_PARTNER_TYPE_ALL
            - ROLE_APP_ADMIN_PARTNER_ORDER_ALL
            - ROLE_APP_ADMIN_PARTNER_BUILDING_SITE_ALL
            - ROLE_APP_ADMIN_SALE_INVOICE_SERIES_ALL
            - ROLE_APP_ADMIN_PAYSLIP_ALL
#            - ROLE_APP_ADMIN_PAYSLIP_LINE_ALL
            - ROLE_APP_ADMIN_PAYSLIP_LINE_CREATE
            - ROLE_APP_ADMIN_PAYSLIP_LINE_EDIT
            - ROLE_APP_ADMIN_PAYSLIP_LINE_DELETE
            - ROLE_APP_ADMIN_PAYSLIP_LINE_CONCEPT_ALL
#            - ROLE_APP_ADMIN_PAYSLIP_OPERATOR_DEFAULT_LINE_ALL
            - ROLE_APP_ADMIN_PAYSLIP_OPERATOR_DEFAULT_LINE_CREATE
            - ROLE_APP_ADMIN_PAYSLIP_OPERATOR_DEFAULT_LINE_EDIT
            - ROLE_APP_ADMIN_PAYSLIP_OPERATOR_DEFAULT_LINE_DELETE
            - ROLE_APP_ADMIN_VEHICLE_MAINTENANCE_ALL
            - ROLE_APP_ADMIN_VEHICLE_MAINTENANCE_TASK_ALL
            - ROLE_APP_ADMIN_VEHICLE_SPECIAL_PERMIT_ALL
            - ROLE_APP_ADMIN_VEHICLE_FUEL_ALL
            - ROLE_APP_ADMIN_PARTNER_DELIVERY_ADDRESS_ALL
        ROLE_CMS:
            - ROLE_USER
            - ROLE_SONATA_CMS
            - ROLE_SONATA_ADMIN
        ROLE_MANAGER:
            - ROLE_CMS
            - ROLE_SONATA_MANAGER
        ROLE_ADMIN:
            - ROLE_MANAGER
            - ROLE_SONATA_MANAGER_ADMIN
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
    access_decision_manager:
        strategy: unanimous
    password_hashers:
#        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Setting\User: bcrypt
    providers:
        app_user_provider:
            entity:
                class: 'App\Entity\Setting\User'
                property: 'username'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: /admin(.*)
#            context: user
            lazy: true
            entry_point: form_login
            form_login:
                provider:                       app_user_provider
                login_path:                     admin_login
                use_forward:                    false
                check_path:                     admin_login
                username_parameter:             'login_form[username]'
                password_parameter:             'login_form[password]'
                csrf_parameter:                 'login_form[_token]'
                failure_path:                   admin_login
                default_target_path:            /admin/dashboard
                always_use_default_target_path: true
                use_referer:                    true
            logout:
                path:   admin_logout
                target: admin_login
#            guard:
#                authenticators:
#                    - App\Security\LoginAuthenticator
        frontend:
            pattern:   ^/(.*)
#            context:   user
            lazy: true
    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_USER }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
