snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: 'redis://localhost'
            logging: '%kernel.debug%'
        doctrine:
            type: predis
            alias: doctrine
            dsn: 'redis://localhost'
            logging: '%kernel.debug%'
    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default
            namespace: 'og4dmc:'
        result_cache:
            client: doctrine
            entity_manager: default
            namespace: 'og4drc:'
        query_cache:
            client: doctrine
            entity_manager: default
            namespace: 'og4dqc:'
        second_level_cache:
            client: doctrine
            entity_manager: default
            namespace: 'og4dslc:'
