stof_doctrine_extensions:
    default_locale: "%default_locale%"
    orm:
        default:
            softdeleteable: true
            timestampable:  true
            sluggable:      true
            translatable:   false
            sortable:       false
            tree:           false
