twig:
    default_path:         '%kernel.project_dir%/templates'
    debug:                '%kernel.debug%'
    strict_variables:     '%kernel.debug%'
    exception_controller: null
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - '@SonataForm/Form/datepicker.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    globals:
        google_analytics_enabled: '%google_analytics_enabled%'
        google_analytics_account: '%google_analytics_account%'
        main_brand_title:         '%project_web_title%'
        admin_brand_title:        '%project_admin_title%'
        admin_tag_version:        'v4.1.23'
        cookieExpiryTime:         90 # days
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true
