vich_uploader:
    db_driver: orm
    mappings:
        service:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/service
            upload_destination: '%kernel.project_dir%/public/uploads/images/service'
        work:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/work
            upload_destination: '%kernel.project_dir%/public/uploads/images/work'
        work_image:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/work_image
            upload_destination: '%kernel.project_dir%/public/uploads/images/work_image'
        vehicle:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/vehicle
            upload_destination: '%kernel.project_dir%/var/uploads/images/vehicle'
        complement:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/complement
            upload_destination: '%kernel.project_dir%/public/uploads/images/complement'
        enterprise:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/enterprise
            upload_destination: '%kernel.project_dir%/var/uploads/images/enterprise'
        operator:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/operator
            upload_destination: '%kernel.project_dir%/var/uploads/images/operator'
        user:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/images/user
            upload_destination: '%kernel.project_dir%/public/uploads/images/user'
        document_vehicle:
            namer:              vich_uploader.namer_uniqid
            uri_prefix:         /uploads/documents/vehicle
            upload_destination: '%kernel.project_dir%/public/uploads/documents/vehicle'
        digital_tachograph_operator:
            uri_prefix:         /uploads/digital_tachograph/operator
            upload_destination: '%kernel.project_dir%/var/uploads/digital_tachograph/operator'
        digital_tachograph_vehicle:
            uri_prefix:         /uploads/digital_tachograph/vehicle
            upload_destination: '%kernel.project_dir%/var/uploads/digital_tachograph/vehicle'
        special_permit_vehicle:
            uri_prefix:         /uploads/special_permit/vehicle
            upload_destination: '%kernel.project_dir%/var/uploads/vehicle/special_permit'
