<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20211202174623 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity_line (id INT AUTO_INCREMENT NOT NULL, enterprise_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_D2D06F64A97D1AC3 (enterprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE admin_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(180) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', UNIQUE INDEX UNIQ_CDEABF3F5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE admin_user (id INT AUTO_INCREMENT NOT NULL, default_enterprise_id INT DEFAULT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, date_of_birth DATETIME DEFAULT NULL, firstname VARCHAR(64) DEFAULT NULL, lastname VARCHAR(64) DEFAULT NULL, website VARCHAR(64) DEFAULT NULL, biography VARCHAR(1000) DEFAULT NULL, gender VARCHAR(1) DEFAULT NULL, locale VARCHAR(8) DEFAULT NULL, timezone VARCHAR(64) DEFAULT NULL, phone VARCHAR(64) DEFAULT NULL, facebook_uid VARCHAR(255) DEFAULT NULL, facebook_name VARCHAR(255) DEFAULT NULL, facebook_data JSON DEFAULT NULL, twitter_uid VARCHAR(255) DEFAULT NULL, twitter_name VARCHAR(255) DEFAULT NULL, twitter_data JSON DEFAULT NULL, gplus_uid VARCHAR(255) DEFAULT NULL, gplus_name VARCHAR(255) DEFAULT NULL, gplus_data JSON DEFAULT NULL, token VARCHAR(255) DEFAULT NULL, two_step_code VARCHAR(255) DEFAULT NULL, main_image VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_AD8A54A992FC23A8 (username_canonical), UNIQUE INDEX UNIQ_AD8A54A9A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_AD8A54A9C05FB297 (confirmation_token), INDEX IDX_AD8A54A99F5C86D0 (default_enterprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE enterprises_users (user_id INT NOT NULL, enterprise_id INT NOT NULL, INDEX IDX_5BB9084A76ED395 (user_id), INDEX IDX_5BB9084A97D1AC3 (enterprise_id), PRIMARY KEY(user_id, enterprise_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fos_user_user_group (user_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_B3C77447A76ED395 (user_id), INDEX IDX_B3C77447FE54D947 (group_id), PRIMARY KEY(user_id, group_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE city (id INT AUTO_INCREMENT NOT NULL, province_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, postal_code VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_2D5B0234E946114A (province_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE collection_document_type (id INT AUTO_INCREMENT NOT NULL, enterprise_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, sit_reference VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_F04B3175A97D1AC3 (enterprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE complement (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(255) NOT NULL, short_description VARCHAR(255) NOT NULL, main_image VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, UNIQUE INDEX UNIQ_F8A41E345E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact_message (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, answer VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) DEFAULT NULL, message TEXT NOT NULL, checked TINYINT(1) NOT NULL, answered TINYINT(1) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE enterprise (id INT AUTO_INCREMENT NOT NULL, city_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, tax_identification_number VARCHAR(255) NOT NULL, business_name VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, phone1 VARCHAR(255) DEFAULT NULL, phone2 VARCHAR(255) DEFAULT NULL, phone3 VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, www VARCHAR(255) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, deed_of_incorporation VARCHAR(255) DEFAULT NULL, tax_identification_number_card VARCHAR(255) DEFAULT NULL, tc1receipt VARCHAR(255) DEFAULT NULL, tc2receipt VARCHAR(255) DEFAULT NULL, ss_registration VARCHAR(255) DEFAULT NULL, ss_payment_certificate VARCHAR(255) DEFAULT NULL, rc1insurance VARCHAR(255) DEFAULT NULL, rc2insurance VARCHAR(255) DEFAULT NULL, rc_receipt VARCHAR(255) DEFAULT NULL, prevention_service_contract VARCHAR(255) DEFAULT NULL, prevention_service_invoice VARCHAR(255) DEFAULT NULL, prevention_service_receipt VARCHAR(255) DEFAULT NULL, occupational_accidents_insurance VARCHAR(255) DEFAULT NULL, occupational_receipt VARCHAR(255) DEFAULT NULL, labor_risk_assessment VARCHAR(255) DEFAULT NULL, security_plan VARCHAR(255) DEFAULT NULL, rea_certificate VARCHAR(255) DEFAULT NULL, oil_certificate VARCHAR(255) DEFAULT NULL, gencat_payment_certificate VARCHAR(255) DEFAULT NULL, deeds_of_powers VARCHAR(255) DEFAULT NULL, iae_registration VARCHAR(255) DEFAULT NULL, iae_receipt VARCHAR(255) DEFAULT NULL, mutual_partnership VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_B1B36A038BAC62AF (city_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE enterprise_group_bounty (id INT AUTO_INCREMENT NOT NULL, enterprise_id INT DEFAULT NULL, group_name VARCHAR(255) NOT NULL, normal_hour DOUBLE PRECISION DEFAULT \'0\', extra_normal_hour DOUBLE PRECISION DEFAULT \'0\', extra_extra_hour DOUBLE PRECISION DEFAULT \'0\', road_normal_hour DOUBLE PRECISION DEFAULT \'0\', road_extra_hour DOUBLE PRECISION DEFAULT \'0\', awaiting_hour DOUBLE PRECISION DEFAULT \'0\', negative_hour DOUBLE PRECISION DEFAULT \'0\', transfer_hour DOUBLE PRECISION DEFAULT \'0\', lunch DOUBLE PRECISION DEFAULT \'0\', dinner DOUBLE PRECISION DEFAULT \'0\', over_night DOUBLE PRECISION DEFAULT \'0\', extra_night DOUBLE PRECISION DEFAULT \'0\', diet DOUBLE PRECISION DEFAULT \'0\', international_lunch DOUBLE PRECISION DEFAULT \'0\', international_dinner DOUBLE PRECISION DEFAULT \'0\', truck_output DOUBLE PRECISION DEFAULT \'0\', car_output DOUBLE PRECISION DEFAULT \'0\', enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_C29186DBA97D1AC3 (enterprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE enterprise_holidays (id INT AUTO_INCREMENT NOT NULL, enterprise_id INT DEFAULT NULL, day DATETIME NOT NULL, name VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_AC0BF137A97D1AC3 (enterprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE enterprise_transfer_account (id INT AUTO_INCREMENT NOT NULL, enterprise_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, iban VARCHAR(255) DEFAULT NULL, swift VARCHAR(255) DEFAULT NULL, bank_code VARCHAR(255) DEFAULT NULL, office_number VARCHAR(255) DEFAULT NULL, control_digit VARCHAR(255) DEFAULT NULL, account_number VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_D3DD4C47A97D1AC3 (enterprise_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE operator (id INT AUTO_INCREMENT NOT NULL, enterprise_id INT DEFAULT NULL, city_id INT DEFAULT NULL, enterprise_group_bounty_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, tax_identification_number VARCHAR(255) NOT NULL, banc_account_number VARCHAR(255) NOT NULL, social_security_number VARCHAR(255) NOT NULL, hour_cost DOUBLE PRECISION DEFAULT NULL, surname1 VARCHAR(255) NOT NULL, surname2 VARCHAR(255) NOT NULL, address VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, enterprise_mobile VARCHAR(255) DEFAULT NULL, own_phone VARCHAR(255) DEFAULT NULL, own_mobile VARCHAR(255) DEFAULT NULL, brith_date DATE NOT NULL, registration_date DATE NOT NULL, profile_photo_image VARCHAR(255) DEFAULT NULL, tax_identification_number_image VARCHAR(255) DEFAULT NULL, driving_license_image VARCHAR(255) DEFAULT NULL, cranes_operator_license_image VARCHAR(255) DEFAULT NULL, medical_check_image VARCHAR(255) DEFAULT NULL, epis_image VARCHAR(255) DEFAULT NULL, training_document_image VARCHAR(255) DEFAULT NULL, information_image VARCHAR(255) DEFAULT NULL, use_of_machinery_authorization_image VARCHAR(255) DEFAULT NULL, discharge_social_security_image VARCHAR(255) DEFAULT NULL, employment_contract_image VARCHAR(255) DEFAULT NULL, has_car_driving_license TINYINT(1) NOT NULL, has_lorry_driving_license TINYINT(1) NOT NULL, has_towing_driving_license TINYINT(1) NOT NULL, has_crane_driving_license TINYINT(1) NOT NULL, shoe_size VARCHAR(255) DEFAULT NULL, jerseyt_size VARCHAR(255) DEFAULT NULL, jacket_size VARCHAR(255) DEFAULT NULL, t_shirt_size VARCHAR(255) DEFAULT NULL, pant_size VARCHAR(255) DEFAULT NULL, working_dress_size VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_D7A6A781A97D1AC3 (enterprise_id), INDEX IDX_D7A6A7818BAC62AF (city_id), INDEX IDX_D7A6A781D4C833C (enterprise_group_bounty_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE operator_absence (id INT AUTO_INCREMENT NOT NULL, operator_id INT DEFAULT NULL, type_id INT DEFAULT NULL, begin DATE NOT NULL, end DATE NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_EB1F38AA584598A3 (operator_id), INDEX IDX_EB1F38AAC54C8C93 (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE operator_absence_type (id INT AUTO_INCREMENT NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, UNIQUE INDEX UNIQ_7403BE215E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE operator_checking_type (id INT AUTO_INCREMENT NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, UNIQUE INDEX UNIQ_2F97D9B15E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE operator_cheking (id INT AUTO_INCREMENT NOT NULL, operator_id INT DEFAULT NULL, type_id INT DEFAULT NULL, begin DATE NOT NULL, end DATE NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_8C8B1610584598A3 (operator_id), INDEX IDX_8C8B1610C54C8C93 (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE operator_digital_tachograph (id INT AUTO_INCREMENT NOT NULL, operator_id INT DEFAULT NULL, uploaded_file_name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_4E559125584598A3 (operator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE operator_various_amount (id INT AUTO_INCREMENT NOT NULL, operator_id INT DEFAULT NULL, date DATE NOT NULL, units INT DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, price_unit DOUBLE PRECISION DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_3A6814E8584598A3 (operator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE operator_work_register (id INT AUTO_INCREMENT NOT NULL, operator_work_register_header_id INT DEFAULT NULL, sale_delivery_note_id INT DEFAULT NULL, start TIME DEFAULT NULL, finish TIME DEFAULT NULL, units DOUBLE PRECISION NOT NULL, price_unit DOUBLE PRECISION NOT NULL, amount DOUBLE PRECISION NOT NULL, description VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_E4A8008818F0890D (operator_work_register_header_id), INDEX IDX_E4A800889C1DE698 (sale_delivery_note_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE operator_work_register_header (id INT AUTO_INCREMENT NOT NULL, operator_id INT DEFAULT NULL, date DATE NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_35F2E9EF584598A3 (operator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE partner (id INT AUTO_INCREMENT NOT NULL, enterprise_id INT DEFAULT NULL, class_id INT DEFAULT NULL, type_id INT DEFAULT NULL, transfer_account_id INT DEFAULT NULL, main_city_id INT DEFAULT NULL, secondary_city_id INT DEFAULT NULL, cif_nif VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, notes TEXT DEFAULT NULL, main_address VARCHAR(255) DEFAULT NULL, secondary_address VARCHAR(255) DEFAULT NULL, phone_number1 VARCHAR(255) DEFAULT NULL, phone_number2 VARCHAR(255) DEFAULT NULL, phone_number3 VARCHAR(255) DEFAULT NULL, phone_number4 VARCHAR(255) DEFAULT NULL, phone_number5 VARCHAR(255) DEFAULT NULL, fax_number1 VARCHAR(255) DEFAULT NULL, fax_number2 VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, www VARCHAR(255) DEFAULT NULL, discount DOUBLE PRECISION DEFAULT NULL, code INT DEFAULT NULL, provider_reference VARCHAR(255) DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, iva_tax_free TINYINT(1) DEFAULT NULL, iban VARCHAR(255) DEFAULT NULL, swift VARCHAR(255) DEFAULT NULL, bank_code VARCHAR(255) DEFAULT NULL, office_number VARCHAR(255) DEFAULT NULL, control_digit VARCHAR(255) DEFAULT NULL, account_number VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_312B3E16A97D1AC3 (enterprise_id), INDEX IDX_312B3E16EA000B10 (class_id), INDEX IDX_312B3E16C54C8C93 (type_id), INDEX IDX_312B3E1641A66153 (transfer_account_id), INDEX IDX_312B3E167FE7CB46 (main_city_id), INDEX IDX_312B3E164EB2946F (secondary_city_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE partner_building_site (id INT AUTO_INCREMENT NOT NULL, partner_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, number VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_839F43F19393F8FE (partner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE partner_class (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE partner_contact (id INT AUTO_INCREMENT NOT NULL, partner_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, care VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, mobile VARCHAR(255) DEFAULT NULL, fax VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_8B8885259393F8FE (partner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE partner_order (id INT AUTO_INCREMENT NOT NULL, partner_id INT DEFAULT NULL, number VARCHAR(255) NOT NULL, provider_reference VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_E6153FFD9393F8FE (partner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE partner_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, account VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE partner_unable_days (id INT AUTO_INCREMENT NOT NULL, partner_id INT DEFAULT NULL, begin DATE NOT NULL, end DATE NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_DFB53CE99393F8FE (partner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payslip (id INT AUTO_INCREMENT NOT NULL, operator_id INT DEFAULT NULL, from_date DATETIME NOT NULL, to_date DATETIME NOT NULL, year INT NOT NULL, expenses DOUBLE PRECISION NOT NULL, social_security_cost DOUBLE PRECISION NOT NULL, extra_pay DOUBLE PRECISION NOT NULL, other_costs DOUBLE PRECISION NOT NULL, total_amount DOUBLE PRECISION NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_9A13CDF0584598A3 (operator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payslip_line (id INT AUTO_INCREMENT NOT NULL, payslip_id INT DEFAULT NULL, payslip_line_concept_id INT DEFAULT NULL, units INT NOT NULL, price_unit DOUBLE PRECISION NOT NULL, amount DOUBLE PRECISION NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_D5ECDDD2296F5EA7 (payslip_id), INDEX IDX_D5ECDDD2F5618732 (payslip_line_concept_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payslip_line_concept (id INT AUTO_INCREMENT NOT NULL, description VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payslip_operator_default_line (id INT AUTO_INCREMENT NOT NULL, operator_id INT DEFAULT NULL, payslip_line_concept_id INT NOT NULL, units DOUBLE PRECISION NOT NULL, price_unit DOUBLE PRECISION NOT NULL, amount DOUBLE PRECISION NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_3C465780584598A3 (operator_id), INDEX IDX_3C465780F5618732 (payslip_line_concept_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE province (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, country VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sale_delivery_note (id INT AUTO_INCREMENT NOT NULL, enterprise_id INT DEFAULT NULL, partner_id INT DEFAULT NULL, building_site_id INT DEFAULT NULL, sale_service_tariff_id INT DEFAULT NULL, vehicle_id INT DEFAULT NULL, secondary_vehicle_id INT DEFAULT NULL, operator_id INT DEFAULT NULL, order_id INT DEFAULT NULL, collection_document_id INT DEFAULT NULL, activity_line_id INT DEFAULT NULL, sale_invoice_id INT DEFAULT NULL, date DATETIME NOT NULL, delivery_note_reference VARCHAR(50) DEFAULT NULL, base_amount DOUBLE PRECISION NOT NULL, discount DOUBLE PRECISION DEFAULT NULL, collection_term INT DEFAULT NULL, wont_be_invoiced TINYINT(1) NOT NULL, is_invoiced TINYINT(1) NOT NULL, service_description VARCHAR(255) DEFAULT NULL, place VARCHAR(255) DEFAULT NULL, observations VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_3FA6B46AA97D1AC3 (enterprise_id), INDEX IDX_3FA6B46A9393F8FE (partner_id), INDEX IDX_3FA6B46AC1759B6C (building_site_id), INDEX IDX_3FA6B46A4EAB1A17 (sale_service_tariff_id), INDEX IDX_3FA6B46A545317D1 (vehicle_id), INDEX IDX_3FA6B46A7D15FA0C (secondary_vehicle_id), INDEX IDX_3FA6B46A584598A3 (operator_id), INDEX IDX_3FA6B46A8D9F6D38 (order_id), INDEX IDX_3FA6B46A5F95E4B6 (collection_document_id), INDEX IDX_3FA6B46A4D2903A2 (activity_line_id), INDEX IDX_3FA6B46AD4DD15B9 (sale_invoice_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sale_delivery_note_line (id INT AUTO_INCREMENT NOT NULL, delivery_note_id INT DEFAULT NULL, sale_item_id INT DEFAULT NULL, units DOUBLE PRECISION DEFAULT NULL, price_unit DOUBLE PRECISION NOT NULL, total DOUBLE PRECISION DEFAULT NULL, discount DOUBLE PRECISION DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, iva DOUBLE PRECISION NOT NULL, irpf DOUBLE PRECISION NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_488879222CF3B78B (delivery_note_id), INDEX IDX_48887922677190CC (sale_item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sale_invoice (id INT AUTO_INCREMENT NOT NULL, partner_id INT DEFAULT NULL, series_id INT DEFAULT NULL, date DATETIME NOT NULL, invoice_number INT NOT NULL, type INT NOT NULL, total DOUBLE PRECISION DEFAULT NULL, base_total DOUBLE PRECISION DEFAULT NULL, iva DOUBLE PRECISION DEFAULT NULL, irpf DOUBLE PRECISION DEFAULT NULL, has_been_counted TINYINT(1) NOT NULL, discount DOUBLE PRECISION DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_E57BD5D69393F8FE (partner_id), INDEX IDX_E57BD5D65278319C (series_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sale_invoice_series (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, prefix VARCHAR(255) DEFAULT NULL, is_default TINYINT(1) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sale_item (id INT AUTO_INCREMENT NOT NULL, description VARCHAR(255) NOT NULL, unit_price DOUBLE PRECISION DEFAULT NULL, type INT NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sale_request (id INT AUTO_INCREMENT NOT NULL, enterprise_id INT DEFAULT NULL, partner_id INT DEFAULT NULL, building_site_id INT DEFAULT NULL, invoice_to_id INT DEFAULT NULL, vehicle_id INT DEFAULT NULL, operator_id INT DEFAULT NULL, tariff_id INT DEFAULT NULL, service_id INT DEFAULT NULL, attended_by_id INT DEFAULT NULL, secondary_vehicle_id INT DEFAULT NULL, contact_person_name VARCHAR(255) DEFAULT NULL, contact_person_phone VARCHAR(255) DEFAULT NULL, contact_person_email VARCHAR(255) DEFAULT NULL, service_description LONGTEXT NOT NULL, height INT DEFAULT NULL, distance INT DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, place LONGTEXT DEFAULT NULL, utensils VARCHAR(255) DEFAULT NULL, observations LONGTEXT DEFAULT NULL, request_date DATE NOT NULL, request_time TIME NOT NULL, service_date DATE NOT NULL, service_time TIME DEFAULT NULL, end_service_time TIME DEFAULT NULL, hour_price DOUBLE PRECISION DEFAULT NULL, minium_hours DOUBLE PRECISION DEFAULT NULL, displacement DOUBLE PRECISION DEFAULT NULL, minium_holiday_hours DOUBLE PRECISION DEFAULT NULL, increase_for_holidays DOUBLE PRECISION DEFAULT NULL, increase_for_holidays_percentage DOUBLE PRECISION DEFAULT NULL, has_been_printed TINYINT(1) NOT NULL, status INT NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_4E894D0DA97D1AC3 (enterprise_id), INDEX IDX_4E894D0D9393F8FE (partner_id), INDEX IDX_4E894D0DC1759B6C (building_site_id), INDEX IDX_4E894D0DDEF1AD0 (invoice_to_id), INDEX IDX_4E894D0D545317D1 (vehicle_id), INDEX IDX_4E894D0D584598A3 (operator_id), INDEX IDX_4E894D0D92348FD2 (tariff_id), INDEX IDX_4E894D0DED5CA9E6 (service_id), INDEX IDX_4E894D0D4A5CE02 (attended_by_id), INDEX IDX_4E894D0D7D15FA0C (secondary_vehicle_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sale_request_has_delivery_note (id INT AUTO_INCREMENT NOT NULL, sale_request_id INT DEFAULT NULL, sale_delivery_note_id INT DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL, total_hours_morning DOUBLE PRECISION DEFAULT NULL, price_hour_morning DOUBLE PRECISION DEFAULT NULL, amount_morning DOUBLE PRECISION DEFAULT NULL, total_hours_afternoon DOUBLE PRECISION DEFAULT NULL, price_hour_afternoon DOUBLE PRECISION DEFAULT NULL, amount_afternoon DOUBLE PRECISION DEFAULT NULL, total_hours_night DOUBLE PRECISION DEFAULT NULL, price_hour_night DOUBLE PRECISION DEFAULT NULL, amount_night DOUBLE PRECISION DEFAULT NULL, total_hours_early_morning DOUBLE PRECISION DEFAULT NULL, price_hour_early_morning DOUBLE PRECISION DEFAULT NULL, amount_early_morning DOUBLE PRECISION DEFAULT NULL, total_hours_displacement DOUBLE PRECISION DEFAULT NULL, price_hour_displacement DOUBLE PRECISION DEFAULT NULL, amount_displacement DOUBLE PRECISION DEFAULT NULL, iva_type DOUBLE PRECISION DEFAULT NULL, retention_type DOUBLE PRECISION DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_6A207146BF2A5CE1 (sale_request_id), INDEX IDX_6A2071469C1DE698 (sale_delivery_note_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sale_service_tariff (id INT AUTO_INCREMENT NOT NULL, activity_line_id INT DEFAULT NULL, description VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_DE484AC4D2903A2 (activity_line_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sale_tariff (id INT AUTO_INCREMENT NOT NULL, enterprise_id INT DEFAULT NULL, sale_service_tariff_id INT DEFAULT NULL, partner_id INT DEFAULT NULL, partner_building_site_id INT DEFAULT NULL, year INT NOT NULL, date DATE DEFAULT NULL, tonnage VARCHAR(255) DEFAULT NULL, price_hour DOUBLE PRECISION DEFAULT NULL, minium_hours DOUBLE PRECISION DEFAULT NULL, minium_holiday_hours DOUBLE PRECISION DEFAULT NULL, displacement DOUBLE PRECISION DEFAULT NULL, increase_for_holidays DOUBLE PRECISION DEFAULT NULL, increase_for_holidays_percentage DOUBLE PRECISION DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_E0042EBFA97D1AC3 (enterprise_id), INDEX IDX_E0042EBF4EAB1A17 (sale_service_tariff_id), INDEX IDX_E0042EBF9393F8FE (partner_id), INDEX IDX_E0042EBF69A34E47 (partner_building_site_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service (id INT AUTO_INCREMENT NOT NULL, vehicle_category_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, main_image VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, position INT DEFAULT 1 NOT NULL, description TEXT DEFAULT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_E19D9AD25E237E06 (name), INDEX IDX_E19D9AD29C7DE094 (vehicle_category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE time_range (id INT AUTO_INCREMENT NOT NULL, description VARCHAR(255) NOT NULL, start TIME NOT NULL, finish TIME NOT NULL, type INT NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicle (id INT AUTO_INCREMENT NOT NULL, vehicle_category_id INT DEFAULT NULL, enterprise_id INT DEFAULT NULL, tonnage_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, vehicle_registration_number VARCHAR(255) NOT NULL, chassis_brand VARCHAR(255) NOT NULL, chassis_number VARCHAR(255) DEFAULT NULL, vehicle_brand VARCHAR(255) DEFAULT NULL, vehicle_model VARCHAR(255) DEFAULT NULL, serial_number VARCHAR(255) DEFAULT NULL, link VARCHAR(255) DEFAULT NULL, attatchment_pdf VARCHAR(255) DEFAULT NULL, main_image VARCHAR(255) DEFAULT NULL, mileage INT NOT NULL, chassis_image VARCHAR(255) DEFAULT NULL, technical_datasheet1 VARCHAR(255) DEFAULT NULL, technical_datasheet2 VARCHAR(255) DEFAULT NULL, load_table VARCHAR(255) DEFAULT NULL, reach_diagram VARCHAR(255) DEFAULT NULL, traffic_certificate VARCHAR(255) DEFAULT NULL, dimensions VARCHAR(255) DEFAULT NULL, transport_card VARCHAR(255) DEFAULT NULL, traffic_insurance VARCHAR(255) DEFAULT NULL, itv VARCHAR(255) DEFAULT NULL, itc VARCHAR(255) DEFAULT NULL, cedeclaration VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_1B80E4865E237E06 (name), INDEX IDX_1B80E4869C7DE094 (vehicle_category_id), INDEX IDX_1B80E486A97D1AC3 (enterprise_id), INDEX IDX_1B80E486FC58EA61 (tonnage_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicle_category (id INT AUTO_INCREMENT NOT NULL, slug VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, name VARCHAR(255) NOT NULL, position INT DEFAULT 1 NOT NULL, UNIQUE INDEX UNIQ_DB5E16555E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicle_checking (id INT AUTO_INCREMENT NOT NULL, vehicle_id INT DEFAULT NULL, type_id INT DEFAULT NULL, begin DATE NOT NULL, end DATE NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_5B2FD42C545317D1 (vehicle_id), INDEX IDX_5B2FD42CC54C8C93 (type_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicle_checking_type (id INT AUTO_INCREMENT NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_16A24EBB5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicle_consumption (id INT AUTO_INCREMENT NOT NULL, vehicle_id INT NOT NULL, vehicle_fuel_id INT DEFAULT NULL, supply_date DATETIME NOT NULL, supply_time TIME DEFAULT NULL, supply_code VARCHAR(255) DEFAULT NULL, amount DOUBLE PRECISION NOT NULL, quantity DOUBLE PRECISION DEFAULT NULL, price_unit DOUBLE PRECISION DEFAULT NULL, fuel_type VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_A2C4508F545317D1 (vehicle_id), INDEX IDX_A2C4508F88B4CB18 (vehicle_fuel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicle_digital_tachograph (id INT AUTO_INCREMENT NOT NULL, vehicle_id INT DEFAULT NULL, uploaded_file_name VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_856FA58545317D1 (vehicle_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicle_fuel (id INT AUTO_INCREMENT NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_43205CB55E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicle_manteinance (id INT AUTO_INCREMENT NOT NULL, vehicle_id INT DEFAULT NULL, vehicle_maintenance_task_id INT DEFAULT NULL, date DATETIME NOT NULL, km INT DEFAULT NULL, needs_check TINYINT(1) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, description TEXT DEFAULT NULL, INDEX IDX_9ECE92B4545317D1 (vehicle_id), INDEX IDX_9ECE92B473AB9475 (vehicle_maintenance_task_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicle_manteinance_task (id INT AUTO_INCREMENT NOT NULL, hours INT DEFAULT NULL, km INT DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_89A6301B5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE vehicle_special_permit (id INT AUTO_INCREMENT NOT NULL, vehicle_id INT DEFAULT NULL, additional_vehicle VARCHAR(255) DEFAULT NULL, additional_registration_number VARCHAR(255) DEFAULT NULL, expedition_date DATE NOT NULL, expiry_date DATE NOT NULL, total_length DOUBLE PRECISION DEFAULT NULL, total_height DOUBLE PRECISION DEFAULT NULL, total_width DOUBLE PRECISION DEFAULT NULL, maximum_weight DOUBLE PRECISION DEFAULT NULL, number_of_axes INT DEFAULT NULL, load_content VARCHAR(255) DEFAULT NULL, expedient_number VARCHAR(255) DEFAULT NULL, route VARCHAR(255) DEFAULT NULL, notes VARCHAR(255) DEFAULT NULL, route_image VARCHAR(255) DEFAULT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_F3CDB4AB545317D1 (vehicle_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE work (id INT AUTO_INCREMENT NOT NULL, service_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, date DATE NOT NULL, short_description VARCHAR(255) DEFAULT NULL, main_image VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, description TEXT DEFAULT NULL, name VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_534E68805E237E06 (name), INDEX IDX_534E6880ED5CA9E6 (service_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE work_image (id INT AUTO_INCREMENT NOT NULL, work_id INT DEFAULT NULL, alt VARCHAR(255) NOT NULL, image VARCHAR(255) NOT NULL, enabled TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, position INT DEFAULT 1 NOT NULL, INDEX IDX_EDC67F70BB3453DB (work_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE activity_line ADD CONSTRAINT FK_D2D06F64A97D1AC3 FOREIGN KEY (enterprise_id) REFERENCES enterprise (id)');
        $this->addSql('ALTER TABLE admin_user ADD CONSTRAINT FK_AD8A54A99F5C86D0 FOREIGN KEY (default_enterprise_id) REFERENCES enterprise (id)');
        $this->addSql('ALTER TABLE enterprises_users ADD CONSTRAINT FK_5BB9084A76ED395 FOREIGN KEY (user_id) REFERENCES admin_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE enterprises_users ADD CONSTRAINT FK_5BB9084A97D1AC3 FOREIGN KEY (enterprise_id) REFERENCES enterprise (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fos_user_user_group ADD CONSTRAINT FK_B3C77447A76ED395 FOREIGN KEY (user_id) REFERENCES admin_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fos_user_user_group ADD CONSTRAINT FK_B3C77447FE54D947 FOREIGN KEY (group_id) REFERENCES admin_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B0234E946114A FOREIGN KEY (province_id) REFERENCES province (id)');
        $this->addSql('ALTER TABLE collection_document_type ADD CONSTRAINT FK_F04B3175A97D1AC3 FOREIGN KEY (enterprise_id) REFERENCES enterprise (id)');
        $this->addSql('ALTER TABLE enterprise ADD CONSTRAINT FK_B1B36A038BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE enterprise_group_bounty ADD CONSTRAINT FK_C29186DBA97D1AC3 FOREIGN KEY (enterprise_id) REFERENCES enterprise (id)');
        $this->addSql('ALTER TABLE enterprise_holidays ADD CONSTRAINT FK_AC0BF137A97D1AC3 FOREIGN KEY (enterprise_id) REFERENCES enterprise (id)');
        $this->addSql('ALTER TABLE enterprise_transfer_account ADD CONSTRAINT FK_D3DD4C47A97D1AC3 FOREIGN KEY (enterprise_id) REFERENCES enterprise (id)');
        $this->addSql('ALTER TABLE operator ADD CONSTRAINT FK_D7A6A781A97D1AC3 FOREIGN KEY (enterprise_id) REFERENCES enterprise (id)');
        $this->addSql('ALTER TABLE operator ADD CONSTRAINT FK_D7A6A7818BAC62AF FOREIGN KEY (city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE operator ADD CONSTRAINT FK_D7A6A781D4C833C FOREIGN KEY (enterprise_group_bounty_id) REFERENCES enterprise_group_bounty (id)');
        $this->addSql('ALTER TABLE operator_absence ADD CONSTRAINT FK_EB1F38AA584598A3 FOREIGN KEY (operator_id) REFERENCES operator (id)');
        $this->addSql('ALTER TABLE operator_absence ADD CONSTRAINT FK_EB1F38AAC54C8C93 FOREIGN KEY (type_id) REFERENCES operator_absence_type (id)');
        $this->addSql('ALTER TABLE operator_cheking ADD CONSTRAINT FK_8C8B1610584598A3 FOREIGN KEY (operator_id) REFERENCES operator (id)');
        $this->addSql('ALTER TABLE operator_cheking ADD CONSTRAINT FK_8C8B1610C54C8C93 FOREIGN KEY (type_id) REFERENCES operator_checking_type (id)');
        $this->addSql('ALTER TABLE operator_digital_tachograph ADD CONSTRAINT FK_4E559125584598A3 FOREIGN KEY (operator_id) REFERENCES operator (id)');
        $this->addSql('ALTER TABLE operator_various_amount ADD CONSTRAINT FK_3A6814E8584598A3 FOREIGN KEY (operator_id) REFERENCES operator (id)');
        $this->addSql('ALTER TABLE operator_work_register ADD CONSTRAINT FK_E4A8008818F0890D FOREIGN KEY (operator_work_register_header_id) REFERENCES operator_work_register_header (id)');
        $this->addSql('ALTER TABLE operator_work_register ADD CONSTRAINT FK_E4A800889C1DE698 FOREIGN KEY (sale_delivery_note_id) REFERENCES sale_delivery_note (id)');
        $this->addSql('ALTER TABLE operator_work_register_header ADD CONSTRAINT FK_35F2E9EF584598A3 FOREIGN KEY (operator_id) REFERENCES operator (id)');
        $this->addSql('ALTER TABLE partner ADD CONSTRAINT FK_312B3E16A97D1AC3 FOREIGN KEY (enterprise_id) REFERENCES enterprise (id)');
        $this->addSql('ALTER TABLE partner ADD CONSTRAINT FK_312B3E16EA000B10 FOREIGN KEY (class_id) REFERENCES partner_class (id)');
        $this->addSql('ALTER TABLE partner ADD CONSTRAINT FK_312B3E16C54C8C93 FOREIGN KEY (type_id) REFERENCES partner_type (id)');
        $this->addSql('ALTER TABLE partner ADD CONSTRAINT FK_312B3E1641A66153 FOREIGN KEY (transfer_account_id) REFERENCES enterprise_transfer_account (id)');
        $this->addSql('ALTER TABLE partner ADD CONSTRAINT FK_312B3E167FE7CB46 FOREIGN KEY (main_city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE partner ADD CONSTRAINT FK_312B3E164EB2946F FOREIGN KEY (secondary_city_id) REFERENCES city (id)');
        $this->addSql('ALTER TABLE partner_building_site ADD CONSTRAINT FK_839F43F19393F8FE FOREIGN KEY (partner_id) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE partner_contact ADD CONSTRAINT FK_8B8885259393F8FE FOREIGN KEY (partner_id) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE partner_order ADD CONSTRAINT FK_E6153FFD9393F8FE FOREIGN KEY (partner_id) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE partner_unable_days ADD CONSTRAINT FK_DFB53CE99393F8FE FOREIGN KEY (partner_id) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE payslip ADD CONSTRAINT FK_9A13CDF0584598A3 FOREIGN KEY (operator_id) REFERENCES operator (id)');
        $this->addSql('ALTER TABLE payslip_line ADD CONSTRAINT FK_D5ECDDD2296F5EA7 FOREIGN KEY (payslip_id) REFERENCES payslip (id)');
        $this->addSql('ALTER TABLE payslip_line ADD CONSTRAINT FK_D5ECDDD2F5618732 FOREIGN KEY (payslip_line_concept_id) REFERENCES payslip_line_concept (id)');
        $this->addSql('ALTER TABLE payslip_operator_default_line ADD CONSTRAINT FK_3C465780584598A3 FOREIGN KEY (operator_id) REFERENCES operator (id)');
        $this->addSql('ALTER TABLE payslip_operator_default_line ADD CONSTRAINT FK_3C465780F5618732 FOREIGN KEY (payslip_line_concept_id) REFERENCES payslip_line_concept (id)');
        $this->addSql('ALTER TABLE sale_delivery_note ADD CONSTRAINT FK_3FA6B46AA97D1AC3 FOREIGN KEY (enterprise_id) REFERENCES enterprise (id)');
        $this->addSql('ALTER TABLE sale_delivery_note ADD CONSTRAINT FK_3FA6B46A9393F8FE FOREIGN KEY (partner_id) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE sale_delivery_note ADD CONSTRAINT FK_3FA6B46AC1759B6C FOREIGN KEY (building_site_id) REFERENCES partner_building_site (id)');
        $this->addSql('ALTER TABLE sale_delivery_note ADD CONSTRAINT FK_3FA6B46A4EAB1A17 FOREIGN KEY (sale_service_tariff_id) REFERENCES sale_service_tariff (id)');
        $this->addSql('ALTER TABLE sale_delivery_note ADD CONSTRAINT FK_3FA6B46A545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id)');
        $this->addSql('ALTER TABLE sale_delivery_note ADD CONSTRAINT FK_3FA6B46A7D15FA0C FOREIGN KEY (secondary_vehicle_id) REFERENCES vehicle (id)');
        $this->addSql('ALTER TABLE sale_delivery_note ADD CONSTRAINT FK_3FA6B46A584598A3 FOREIGN KEY (operator_id) REFERENCES operator (id)');
        $this->addSql('ALTER TABLE sale_delivery_note ADD CONSTRAINT FK_3FA6B46A8D9F6D38 FOREIGN KEY (order_id) REFERENCES partner_order (id)');
        $this->addSql('ALTER TABLE sale_delivery_note ADD CONSTRAINT FK_3FA6B46A5F95E4B6 FOREIGN KEY (collection_document_id) REFERENCES collection_document_type (id)');
        $this->addSql('ALTER TABLE sale_delivery_note ADD CONSTRAINT FK_3FA6B46A4D2903A2 FOREIGN KEY (activity_line_id) REFERENCES activity_line (id)');
        $this->addSql('ALTER TABLE sale_delivery_note ADD CONSTRAINT FK_3FA6B46AD4DD15B9 FOREIGN KEY (sale_invoice_id) REFERENCES sale_invoice (id)');
        $this->addSql('ALTER TABLE sale_delivery_note_line ADD CONSTRAINT FK_488879222CF3B78B FOREIGN KEY (delivery_note_id) REFERENCES sale_delivery_note (id)');
        $this->addSql('ALTER TABLE sale_delivery_note_line ADD CONSTRAINT FK_48887922677190CC FOREIGN KEY (sale_item_id) REFERENCES sale_item (id)');
        $this->addSql('ALTER TABLE sale_invoice ADD CONSTRAINT FK_E57BD5D69393F8FE FOREIGN KEY (partner_id) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE sale_invoice ADD CONSTRAINT FK_E57BD5D65278319C FOREIGN KEY (series_id) REFERENCES sale_invoice_series (id)');
        $this->addSql('ALTER TABLE sale_request ADD CONSTRAINT FK_4E894D0DA97D1AC3 FOREIGN KEY (enterprise_id) REFERENCES enterprise (id)');
        $this->addSql('ALTER TABLE sale_request ADD CONSTRAINT FK_4E894D0D9393F8FE FOREIGN KEY (partner_id) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE sale_request ADD CONSTRAINT FK_4E894D0DC1759B6C FOREIGN KEY (building_site_id) REFERENCES partner_building_site (id)');
        $this->addSql('ALTER TABLE sale_request ADD CONSTRAINT FK_4E894D0DDEF1AD0 FOREIGN KEY (invoice_to_id) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE sale_request ADD CONSTRAINT FK_4E894D0D545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id)');
        $this->addSql('ALTER TABLE sale_request ADD CONSTRAINT FK_4E894D0D584598A3 FOREIGN KEY (operator_id) REFERENCES operator (id)');
        $this->addSql('ALTER TABLE sale_request ADD CONSTRAINT FK_4E894D0D92348FD2 FOREIGN KEY (tariff_id) REFERENCES sale_tariff (id)');
        $this->addSql('ALTER TABLE sale_request ADD CONSTRAINT FK_4E894D0DED5CA9E6 FOREIGN KEY (service_id) REFERENCES sale_service_tariff (id)');
        $this->addSql('ALTER TABLE sale_request ADD CONSTRAINT FK_4E894D0D4A5CE02 FOREIGN KEY (attended_by_id) REFERENCES admin_user (id)');
        $this->addSql('ALTER TABLE sale_request ADD CONSTRAINT FK_4E894D0D7D15FA0C FOREIGN KEY (secondary_vehicle_id) REFERENCES vehicle (id)');
        $this->addSql('ALTER TABLE sale_request_has_delivery_note ADD CONSTRAINT FK_6A207146BF2A5CE1 FOREIGN KEY (sale_request_id) REFERENCES sale_request (id)');
        $this->addSql('ALTER TABLE sale_request_has_delivery_note ADD CONSTRAINT FK_6A2071469C1DE698 FOREIGN KEY (sale_delivery_note_id) REFERENCES sale_delivery_note (id)');
        $this->addSql('ALTER TABLE sale_service_tariff ADD CONSTRAINT FK_DE484AC4D2903A2 FOREIGN KEY (activity_line_id) REFERENCES activity_line (id)');
        $this->addSql('ALTER TABLE sale_tariff ADD CONSTRAINT FK_E0042EBFA97D1AC3 FOREIGN KEY (enterprise_id) REFERENCES enterprise (id)');
        $this->addSql('ALTER TABLE sale_tariff ADD CONSTRAINT FK_E0042EBF4EAB1A17 FOREIGN KEY (sale_service_tariff_id) REFERENCES sale_service_tariff (id)');
        $this->addSql('ALTER TABLE sale_tariff ADD CONSTRAINT FK_E0042EBF9393F8FE FOREIGN KEY (partner_id) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE sale_tariff ADD CONSTRAINT FK_E0042EBF69A34E47 FOREIGN KEY (partner_building_site_id) REFERENCES partner_building_site (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD29C7DE094 FOREIGN KEY (vehicle_category_id) REFERENCES vehicle_category (id)');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E4869C7DE094 FOREIGN KEY (vehicle_category_id) REFERENCES vehicle_category (id)');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E486A97D1AC3 FOREIGN KEY (enterprise_id) REFERENCES enterprise (id)');
        $this->addSql('ALTER TABLE vehicle ADD CONSTRAINT FK_1B80E486FC58EA61 FOREIGN KEY (tonnage_id) REFERENCES sale_service_tariff (id)');
        $this->addSql('ALTER TABLE vehicle_checking ADD CONSTRAINT FK_5B2FD42C545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id)');
        $this->addSql('ALTER TABLE vehicle_checking ADD CONSTRAINT FK_5B2FD42CC54C8C93 FOREIGN KEY (type_id) REFERENCES vehicle_checking_type (id)');
        $this->addSql('ALTER TABLE vehicle_consumption ADD CONSTRAINT FK_A2C4508F545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id)');
        $this->addSql('ALTER TABLE vehicle_consumption ADD CONSTRAINT FK_A2C4508F88B4CB18 FOREIGN KEY (vehicle_fuel_id) REFERENCES vehicle_fuel (id)');
        $this->addSql('ALTER TABLE vehicle_digital_tachograph ADD CONSTRAINT FK_856FA58545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id)');
        $this->addSql('ALTER TABLE vehicle_manteinance ADD CONSTRAINT FK_9ECE92B4545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id)');
        $this->addSql('ALTER TABLE vehicle_manteinance ADD CONSTRAINT FK_9ECE92B473AB9475 FOREIGN KEY (vehicle_maintenance_task_id) REFERENCES vehicle_manteinance_task (id)');
        $this->addSql('ALTER TABLE vehicle_special_permit ADD CONSTRAINT FK_F3CDB4AB545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id)');
        $this->addSql('ALTER TABLE work ADD CONSTRAINT FK_534E6880ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id)');
        $this->addSql('ALTER TABLE work_image ADD CONSTRAINT FK_EDC67F70BB3453DB FOREIGN KEY (work_id) REFERENCES work (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE sale_delivery_note DROP FOREIGN KEY FK_3FA6B46A4D2903A2');
        $this->addSql('ALTER TABLE sale_service_tariff DROP FOREIGN KEY FK_DE484AC4D2903A2');
        $this->addSql('ALTER TABLE fos_user_user_group DROP FOREIGN KEY FK_B3C77447FE54D947');
        $this->addSql('ALTER TABLE enterprises_users DROP FOREIGN KEY FK_5BB9084A76ED395');
        $this->addSql('ALTER TABLE fos_user_user_group DROP FOREIGN KEY FK_B3C77447A76ED395');
        $this->addSql('ALTER TABLE sale_request DROP FOREIGN KEY FK_4E894D0D4A5CE02');
        $this->addSql('ALTER TABLE enterprise DROP FOREIGN KEY FK_B1B36A038BAC62AF');
        $this->addSql('ALTER TABLE operator DROP FOREIGN KEY FK_D7A6A7818BAC62AF');
        $this->addSql('ALTER TABLE partner DROP FOREIGN KEY FK_312B3E167FE7CB46');
        $this->addSql('ALTER TABLE partner DROP FOREIGN KEY FK_312B3E164EB2946F');
        $this->addSql('ALTER TABLE sale_delivery_note DROP FOREIGN KEY FK_3FA6B46A5F95E4B6');
        $this->addSql('ALTER TABLE activity_line DROP FOREIGN KEY FK_D2D06F64A97D1AC3');
        $this->addSql('ALTER TABLE admin_user DROP FOREIGN KEY FK_AD8A54A99F5C86D0');
        $this->addSql('ALTER TABLE enterprises_users DROP FOREIGN KEY FK_5BB9084A97D1AC3');
        $this->addSql('ALTER TABLE collection_document_type DROP FOREIGN KEY FK_F04B3175A97D1AC3');
        $this->addSql('ALTER TABLE enterprise_group_bounty DROP FOREIGN KEY FK_C29186DBA97D1AC3');
        $this->addSql('ALTER TABLE enterprise_holidays DROP FOREIGN KEY FK_AC0BF137A97D1AC3');
        $this->addSql('ALTER TABLE enterprise_transfer_account DROP FOREIGN KEY FK_D3DD4C47A97D1AC3');
        $this->addSql('ALTER TABLE operator DROP FOREIGN KEY FK_D7A6A781A97D1AC3');
        $this->addSql('ALTER TABLE partner DROP FOREIGN KEY FK_312B3E16A97D1AC3');
        $this->addSql('ALTER TABLE sale_delivery_note DROP FOREIGN KEY FK_3FA6B46AA97D1AC3');
        $this->addSql('ALTER TABLE sale_request DROP FOREIGN KEY FK_4E894D0DA97D1AC3');
        $this->addSql('ALTER TABLE sale_tariff DROP FOREIGN KEY FK_E0042EBFA97D1AC3');
        $this->addSql('ALTER TABLE vehicle DROP FOREIGN KEY FK_1B80E486A97D1AC3');
        $this->addSql('ALTER TABLE operator DROP FOREIGN KEY FK_D7A6A781D4C833C');
        $this->addSql('ALTER TABLE partner DROP FOREIGN KEY FK_312B3E1641A66153');
        $this->addSql('ALTER TABLE operator_absence DROP FOREIGN KEY FK_EB1F38AA584598A3');
        $this->addSql('ALTER TABLE operator_cheking DROP FOREIGN KEY FK_8C8B1610584598A3');
        $this->addSql('ALTER TABLE operator_digital_tachograph DROP FOREIGN KEY FK_4E559125584598A3');
        $this->addSql('ALTER TABLE operator_various_amount DROP FOREIGN KEY FK_3A6814E8584598A3');
        $this->addSql('ALTER TABLE operator_work_register_header DROP FOREIGN KEY FK_35F2E9EF584598A3');
        $this->addSql('ALTER TABLE payslip DROP FOREIGN KEY FK_9A13CDF0584598A3');
        $this->addSql('ALTER TABLE payslip_operator_default_line DROP FOREIGN KEY FK_3C465780584598A3');
        $this->addSql('ALTER TABLE sale_delivery_note DROP FOREIGN KEY FK_3FA6B46A584598A3');
        $this->addSql('ALTER TABLE sale_request DROP FOREIGN KEY FK_4E894D0D584598A3');
        $this->addSql('ALTER TABLE operator_absence DROP FOREIGN KEY FK_EB1F38AAC54C8C93');
        $this->addSql('ALTER TABLE operator_cheking DROP FOREIGN KEY FK_8C8B1610C54C8C93');
        $this->addSql('ALTER TABLE operator_work_register DROP FOREIGN KEY FK_E4A8008818F0890D');
        $this->addSql('ALTER TABLE partner_building_site DROP FOREIGN KEY FK_839F43F19393F8FE');
        $this->addSql('ALTER TABLE partner_contact DROP FOREIGN KEY FK_8B8885259393F8FE');
        $this->addSql('ALTER TABLE partner_order DROP FOREIGN KEY FK_E6153FFD9393F8FE');
        $this->addSql('ALTER TABLE partner_unable_days DROP FOREIGN KEY FK_DFB53CE99393F8FE');
        $this->addSql('ALTER TABLE sale_delivery_note DROP FOREIGN KEY FK_3FA6B46A9393F8FE');
        $this->addSql('ALTER TABLE sale_invoice DROP FOREIGN KEY FK_E57BD5D69393F8FE');
        $this->addSql('ALTER TABLE sale_request DROP FOREIGN KEY FK_4E894D0D9393F8FE');
        $this->addSql('ALTER TABLE sale_request DROP FOREIGN KEY FK_4E894D0DDEF1AD0');
        $this->addSql('ALTER TABLE sale_tariff DROP FOREIGN KEY FK_E0042EBF9393F8FE');
        $this->addSql('ALTER TABLE sale_delivery_note DROP FOREIGN KEY FK_3FA6B46AC1759B6C');
        $this->addSql('ALTER TABLE sale_request DROP FOREIGN KEY FK_4E894D0DC1759B6C');
        $this->addSql('ALTER TABLE sale_tariff DROP FOREIGN KEY FK_E0042EBF69A34E47');
        $this->addSql('ALTER TABLE partner DROP FOREIGN KEY FK_312B3E16EA000B10');
        $this->addSql('ALTER TABLE sale_delivery_note DROP FOREIGN KEY FK_3FA6B46A8D9F6D38');
        $this->addSql('ALTER TABLE partner DROP FOREIGN KEY FK_312B3E16C54C8C93');
        $this->addSql('ALTER TABLE payslip_line DROP FOREIGN KEY FK_D5ECDDD2296F5EA7');
        $this->addSql('ALTER TABLE payslip_line DROP FOREIGN KEY FK_D5ECDDD2F5618732');
        $this->addSql('ALTER TABLE payslip_operator_default_line DROP FOREIGN KEY FK_3C465780F5618732');
        $this->addSql('ALTER TABLE city DROP FOREIGN KEY FK_2D5B0234E946114A');
        $this->addSql('ALTER TABLE operator_work_register DROP FOREIGN KEY FK_E4A800889C1DE698');
        $this->addSql('ALTER TABLE sale_delivery_note_line DROP FOREIGN KEY FK_488879222CF3B78B');
        $this->addSql('ALTER TABLE sale_request_has_delivery_note DROP FOREIGN KEY FK_6A2071469C1DE698');
        $this->addSql('ALTER TABLE sale_delivery_note DROP FOREIGN KEY FK_3FA6B46AD4DD15B9');
        $this->addSql('ALTER TABLE sale_invoice DROP FOREIGN KEY FK_E57BD5D65278319C');
        $this->addSql('ALTER TABLE sale_delivery_note_line DROP FOREIGN KEY FK_48887922677190CC');
        $this->addSql('ALTER TABLE sale_request_has_delivery_note DROP FOREIGN KEY FK_6A207146BF2A5CE1');
        $this->addSql('ALTER TABLE sale_delivery_note DROP FOREIGN KEY FK_3FA6B46A4EAB1A17');
        $this->addSql('ALTER TABLE sale_request DROP FOREIGN KEY FK_4E894D0DED5CA9E6');
        $this->addSql('ALTER TABLE sale_tariff DROP FOREIGN KEY FK_E0042EBF4EAB1A17');
        $this->addSql('ALTER TABLE vehicle DROP FOREIGN KEY FK_1B80E486FC58EA61');
        $this->addSql('ALTER TABLE sale_request DROP FOREIGN KEY FK_4E894D0D92348FD2');
        $this->addSql('ALTER TABLE work DROP FOREIGN KEY FK_534E6880ED5CA9E6');
        $this->addSql('ALTER TABLE sale_delivery_note DROP FOREIGN KEY FK_3FA6B46A545317D1');
        $this->addSql('ALTER TABLE sale_delivery_note DROP FOREIGN KEY FK_3FA6B46A7D15FA0C');
        $this->addSql('ALTER TABLE sale_request DROP FOREIGN KEY FK_4E894D0D545317D1');
        $this->addSql('ALTER TABLE sale_request DROP FOREIGN KEY FK_4E894D0D7D15FA0C');
        $this->addSql('ALTER TABLE vehicle_checking DROP FOREIGN KEY FK_5B2FD42C545317D1');
        $this->addSql('ALTER TABLE vehicle_consumption DROP FOREIGN KEY FK_A2C4508F545317D1');
        $this->addSql('ALTER TABLE vehicle_digital_tachograph DROP FOREIGN KEY FK_856FA58545317D1');
        $this->addSql('ALTER TABLE vehicle_manteinance DROP FOREIGN KEY FK_9ECE92B4545317D1');
        $this->addSql('ALTER TABLE vehicle_special_permit DROP FOREIGN KEY FK_F3CDB4AB545317D1');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD29C7DE094');
        $this->addSql('ALTER TABLE vehicle DROP FOREIGN KEY FK_1B80E4869C7DE094');
        $this->addSql('ALTER TABLE vehicle_checking DROP FOREIGN KEY FK_5B2FD42CC54C8C93');
        $this->addSql('ALTER TABLE vehicle_consumption DROP FOREIGN KEY FK_A2C4508F88B4CB18');
        $this->addSql('ALTER TABLE vehicle_manteinance DROP FOREIGN KEY FK_9ECE92B473AB9475');
        $this->addSql('ALTER TABLE work_image DROP FOREIGN KEY FK_EDC67F70BB3453DB');
        $this->addSql('DROP TABLE activity_line');
        $this->addSql('DROP TABLE admin_group');
        $this->addSql('DROP TABLE admin_user');
        $this->addSql('DROP TABLE enterprises_users');
        $this->addSql('DROP TABLE fos_user_user_group');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE collection_document_type');
        $this->addSql('DROP TABLE complement');
        $this->addSql('DROP TABLE contact_message');
        $this->addSql('DROP TABLE enterprise');
        $this->addSql('DROP TABLE enterprise_group_bounty');
        $this->addSql('DROP TABLE enterprise_holidays');
        $this->addSql('DROP TABLE enterprise_transfer_account');
        $this->addSql('DROP TABLE operator');
        $this->addSql('DROP TABLE operator_absence');
        $this->addSql('DROP TABLE operator_absence_type');
        $this->addSql('DROP TABLE operator_checking_type');
        $this->addSql('DROP TABLE operator_cheking');
        $this->addSql('DROP TABLE operator_digital_tachograph');
        $this->addSql('DROP TABLE operator_various_amount');
        $this->addSql('DROP TABLE operator_work_register');
        $this->addSql('DROP TABLE operator_work_register_header');
        $this->addSql('DROP TABLE partner');
        $this->addSql('DROP TABLE partner_building_site');
        $this->addSql('DROP TABLE partner_class');
        $this->addSql('DROP TABLE partner_contact');
        $this->addSql('DROP TABLE partner_order');
        $this->addSql('DROP TABLE partner_type');
        $this->addSql('DROP TABLE partner_unable_days');
        $this->addSql('DROP TABLE payslip');
        $this->addSql('DROP TABLE payslip_line');
        $this->addSql('DROP TABLE payslip_line_concept');
        $this->addSql('DROP TABLE payslip_operator_default_line');
        $this->addSql('DROP TABLE province');
        $this->addSql('DROP TABLE sale_delivery_note');
        $this->addSql('DROP TABLE sale_delivery_note_line');
        $this->addSql('DROP TABLE sale_invoice');
        $this->addSql('DROP TABLE sale_invoice_series');
        $this->addSql('DROP TABLE sale_item');
        $this->addSql('DROP TABLE sale_request');
        $this->addSql('DROP TABLE sale_request_has_delivery_note');
        $this->addSql('DROP TABLE sale_service_tariff');
        $this->addSql('DROP TABLE sale_tariff');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE time_range');
        $this->addSql('DROP TABLE vehicle');
        $this->addSql('DROP TABLE vehicle_category');
        $this->addSql('DROP TABLE vehicle_checking');
        $this->addSql('DROP TABLE vehicle_checking_type');
        $this->addSql('DROP TABLE vehicle_consumption');
        $this->addSql('DROP TABLE vehicle_digital_tachograph');
        $this->addSql('DROP TABLE vehicle_fuel');
        $this->addSql('DROP TABLE vehicle_manteinance');
        $this->addSql('DROP TABLE vehicle_manteinance_task');
        $this->addSql('DROP TABLE vehicle_special_permit');
        $this->addSql('DROP TABLE work');
        $this->addSql('DROP TABLE work_image');
    }
}
