# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    default_locale:            '%env(string:DEFAULT_LOCALE)%'
    database_server_version:   '%env(resolve:DATABASE_SERVER_VERSION)%'
    project_web_title:         '%env(string:PROJECT_WEB_TITLE)%'
    project_url_base:          '%env(string:PROJECT_BASE_URL)%'
    google_analytics_enabled:  '%env(bool:GOOGLE_ANALYTICS_IS_ENABLED)%'
    google_analytics_account:  '%env(string:GOOGLE_ANALYTICS_ACCOUNT)%'
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
    google_maps_api_key:       '%env(string:GOOGLE_MAPS_API_KEY)%'
    delivery_dev_address:      '%env(string:DEV_DELIVERY_ADDRESS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
