# Enterprise group
services:
    app.admin.enterprise:
        class: App\Admin\Enterprise\EnterpriseAdmin
        arguments: [ ~, App\Entity\Enterprise\Enterprise, App\Controller\Admin\Enterprise\EnterpriseAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker" , "@security.password_encoder"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Empresa", group: "Configuración", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.enterprise_group_bounty:
        class: App\Admin\Enterprise\EnterpriseGroupBountyAdmin
        arguments: [ ~, App\Entity\Enterprise\EnterpriseGroupBounty, App\Controller\Admin\Enterprise\EnterpriseGroupBountyAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.password_encoder" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Complementos salariales", group: "Configuración", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.enterprise_transfer_account:
        class: App\Admin\Enterprise\EnterpriseTransferAccountAdmin
        arguments: [ ~, App\Entity\Enterprise\EnterpriseTransferAccount, App\Controller\Admin\Enterprise\EnterpriseTransferAccountAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.password_encoder"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Cuenta bancaria", group: "Configuración", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.enterprise_holidays:
        class: App\Admin\Enterprise\EnterpriseHolidaysAdmin
        arguments: [ ~, App\Entity\Enterprise\EnterpriseHolidays, App\Controller\Admin\Enterprise\EnterpriseHolidaysAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.password_encoder"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Dias festivos", group: "Configuración", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.activity_line:
        class: App\Admin\Enterprise\ActivityLineAdmin
        arguments: [ ~, App\Entity\Enterprise\ActivityLine, App\Controller\Admin\Enterprise\ActivityLineAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.password_encoder"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Líneas actividad", group: "Configuración", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.collection_document_type:
        class: App\Admin\Enterprise\CollectionDocumentTypeAdmin
        arguments: [ ~, App\Entity\Enterprise\CollectionDocumentType, App\Controller\Admin\Enterprise\CollectionDocumentTypeAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.password_encoder"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tipo documentos de cobro", group: "Configuración", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTranslationDomain, [ "admin" ] ]
