# Operator group
services:
    app.admin.operator:
        class: App\Admin\Operator\OperatorAdmin
        arguments: [ ~, App\Entity\Operator\Operator, App\Controller\Admin\Operator\OperatorAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Operari", group: "Operaris", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.operator_checking_type:
        class: App\Admin\Operator\OperatorCheckingTypeAdmin
        arguments: [ ~, App\Entity\Operator\OperatorCheckingType, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tipus revisió", group: "Operaris", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.operator_checking:
        class: App\Admin\Operator\OperatorCheckingAdmin
        arguments: [ ~, App\Entity\Operator\OperatorChecking, App\Controller\Admin\Operator\OperatorCheckingAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Revisió", group: "Operaris", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.operator_absence_type:
        class: App\Admin\Operator\OperatorAbsenceTypeAdmin
        arguments: [ ~, App\Entity\Operator\OperatorAbsenceType, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tipus absència", group: "Operaris", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.operator_absence:
        class: App\Admin\Operator\OperatorAbsenceAdmin
        arguments: [ ~, App\Entity\Operator\OperatorAbsence, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Absència", group: "Operaris", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.operator.digital_tachograph:
        class: App\Admin\Operator\OperatorDigitalTachographAdmin
        arguments: [ ~, App\Entity\Operator\OperatorDigitalTachograph, App\Controller\Admin\Operator\OperatorDigitalTachographAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tacògraf", group: "Operaris", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.operator.various_amount:
        class: App\Admin\Operator\OperatorVariousAmountAdmin
        arguments: [ ~, App\Entity\Operator\OperatorVariousAmount, App\Controller\Admin\Operator\OperatorVariousAmountAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Imports varis", group: "Operaris", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.operator_work_register:
        class: App\Admin\Operator\OperatorWorkRegisterAdmin
        arguments: [ ~, App\Entity\Operator\OperatorWorkRegister, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Partes de trabajo", group: "Operaris", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTemplate, [ edit, "admin/operator-work-register/edit.html.twig" ] ]
