# Partner group
services:
    app.admin.client.partner:
        class: App\Admin\Partner\ClientPartnerAdmin
        arguments: [ ~, App\Entity\Partner\Partner, App\Controller\Admin\Partner\PartnerAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Clientes", group: "Terceros", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.partner:
        class: App\Admin\Partner\PartnerAdmin
        arguments: [ 'partner_admin', App\Entity\Partner\Partner, App\Controller\Admin\Partner\PartnerAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tercer", group: "Terceros", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.partner_class:
        class: App\Admin\Partner\PartnerClassAdmin
        arguments: [ ~, App\Entity\Partner\PartnerClass, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Classe", group: "Terceros", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.partner_type:
        class: App\Admin\Partner\PartnerTypeAdmin
        arguments: [ ~, App\Entity\Partner\PartnerType, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tipus", group: "Terceros", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.partner_order:
        class: App\Admin\Partner\PartnerOrderAdmin
        arguments: [ ~, App\Entity\Partner\PartnerOrder, App\Controller\Admin\Partner\PartnerOrderAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Comandes", group: "Terceros", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.partner_building_site:
        class: App\Admin\Partner\PartnerBuildingSiteAdmin
        arguments: [ ~, App\Entity\Partner\PartnerBuildingSite, App\Controller\Admin\Partner\PartnerBuildingSiteAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Obres", group: "Terceros", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.partner_contact:
        class: App\Admin\Partner\PartnerContactAdmin
        arguments: [ ~, App\Entity\Partner\PartnerContact, App\Controller\Admin\Partner\PartnerContactAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Contacte", group: "Terceros", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.partner_unable_days:
        class: App\Admin\Partner\PartnerUnableDaysAdmin
        arguments: [ ~, App\Entity\Partner\PartnerUnableDays, App\Controller\Admin\Partner\PartnerUnableDaysAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Dies inhàbils", group: "Terceros", label_translator_strategy: "sonata.admin.label.strategy.noop" }
