# Sale group
services:
  app.admin.payslip_line_concept:
    class: App\Admin\Payslip\PayslipLineConceptAdmin
    arguments: [ ~, App\Entity\Payslip\PayslipLineConcept, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Conceptos de línia", group: "Nóminas", label_translator_strategy: "sonata.admin.label.strategy.noop" }
  app.admin.payslip_operator_default_line:
    class: App\Admin\Payslip\PayslipOperatorDefaultLineAdmin
    arguments: [ ~, App\Entity\Payslip\PayslipOperatorDefaultLine, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
    tags:
      - { name: sonata.admin, manager_type: orm, label: "Conceptos de línia - operario por defecto", group: "Nóminas", label_translator_strategy: "sonata.admin.label.strategy.noop" }
