# Sale group
services:
    app.admin.sale_tariff:
        class: App\Admin\Sale\SaleTariffAdmin
        arguments: [ '@liip_imagine.cache.manager', '@App\Manager\YearChoicesManager', '@App\Manager\InvoiceManager', '@App\Manager\RepositoriesManager', '@App\Manager\DeliveryNoteManager','@App\Manager\VehicleMaintenanceManager', '@doctrine.orm.entity_manager', '@App\Service\FileService', '@twig', '@security.token_storage', '@security.authorization_checker','@security.user_password_hasher']
        tags:
            - { name: sonata.admin, code:  ~, model_class: App\Entity\Sale\SaleTariff, controller: App\Controller\Admin\Sale\SaleTariffAdminController, manager_type: orm, label: 'Tarifa', group: 'Ventas', label_translator_strategy: 'sonata.admin.label.strategy.noop' }
        calls:
            - [ setTemplate, [ edit, 'admin/sale-tariff/edit.html.twig' ] ]
            - [ setTranslationDomain, [ 'admin' ] ]
    app.admin.sale_request:
        class: App\Admin\Sale\SaleRequestAdmin
        arguments: [ '@liip_imagine.cache.manager', '@App\Manager\YearChoicesManager', '@App\Manager\InvoiceManager', '@App\Manager\RepositoriesManager', '@App\Manager\DeliveryNoteManager','@App\Manager\VehicleMaintenanceManager', '@doctrine.orm.entity_manager', '@App\Service\FileService', '@twig', '@security.token_storage', '@security.authorization_checker','@security.user_password_hasher']
        tags:
            - { name: sonata.admin, code:  ~, model_class: App\Entity\Sale\SaleRequest, controller: App\Controller\Admin\Sale\SaleRequestAdminController, manager_type: orm, label: 'Petición', group: 'Ventas', label_translator_strategy: 'sonata.admin.label.strategy.noop' }
        calls:
            - [ setTemplate, [ edit, 'admin/sale-request/edit.html.twig' ] ]
            - [ setTranslationDomain, [ 'admin' ] ]
    app.admin.sale_delivery_note:
        class: App\Admin\Sale\SaleDeliveryNoteAdmin
        arguments: [ '@liip_imagine.cache.manager', '@App\Manager\YearChoicesManager', '@App\Manager\InvoiceManager', '@App\Manager\RepositoriesManager', '@App\Manager\DeliveryNoteManager','@App\Manager\VehicleMaintenanceManager', '@doctrine.orm.entity_manager', '@App\Service\FileService', '@twig', '@security.token_storage', '@security.authorization_checker','@security.user_password_hasher']
        tags:
            - { name: sonata.admin, code:  ~, model_class: App\Entity\Sale\SaleDeliveryNote, controller: App\Controller\Admin\Sale\SaleDeliveryNoteAdminController, manager_type: orm, label: 'Listar albaranes', group: 'Ventas', label_translator_strategy: 'sonata.admin.label.strategy.noop', default: true }
        calls:
            - [ setTemplate, [ edit, 'admin/sale-delivery-note/edit.html.twig' ] ]
            - [ setTranslationDomain, [ 'admin' ] ]
    app.admin.sale_delivery_note_to_invoice_custom:
        class: App\Admin\Sale\SaleDeliveryNoteToInvoiceCustomAdmin
        arguments: [ '@liip_imagine.cache.manager', '@App\Manager\YearChoicesManager', '@App\Manager\InvoiceManager', '@App\Manager\RepositoriesManager', '@App\Manager\DeliveryNoteManager','@App\Manager\VehicleMaintenanceManager', '@doctrine.orm.entity_manager', '@App\Service\FileService', '@twig', '@security.token_storage', '@security.authorization_checker','@security.user_password_hasher']
        tags:
            - { name: sonata.admin, code:  ~, model_class: App\Entity\Sale\SaleDeliveryNote, controller: App\Controller\Admin\Sale\SaleDeliveryNoteAdminController, manager_type: orm, label: 'Valorar albaranes', group: 'Ventas', label_translator_strategy: 'sonata.admin.label.strategy.noop' }
        calls:
            - [ setTemplate, [ edit, 'admin/sale-delivery-note/edit.html.twig' ] ]
            - [ setTranslationDomain, [ 'admin' ] ]
    app.admin.sale_delivery_note_line:
        class: App\Admin\Sale\SaleDeliveryNoteLineAdmin
        arguments: [ '@liip_imagine.cache.manager', '@App\Manager\YearChoicesManager', '@App\Manager\InvoiceManager', '@App\Manager\RepositoriesManager', '@App\Manager\DeliveryNoteManager','@App\Manager\VehicleMaintenanceManager', '@doctrine.orm.entity_manager', '@App\Service\FileService', '@twig', '@security.token_storage', '@security.authorization_checker','@security.user_password_hasher']
        tags:
            - { name: sonata.admin, code:  ~, model_class: App\Entity\Sale\SaleDeliveryNoteLine, controller: App\Controller\Admin\Sale\SaleDeliveryNoteLineAdminController, manager_type: orm, label: 'Albarán línea', group: 'Ventas', label_translator_strategy: 'sonata.admin.label.strategy.noop', show_in_dashboard: false}
        calls:
            - [ setTranslationDomain, [ 'admin' ] ]
    app.admin.sale_invoice:
        class: App\Admin\Sale\SaleInvoiceAdmin
        arguments: [ '@liip_imagine.cache.manager', '@App\Manager\YearChoicesManager', '@App\Manager\InvoiceManager', '@App\Manager\RepositoriesManager', '@App\Manager\DeliveryNoteManager','@App\Manager\VehicleMaintenanceManager', '@doctrine.orm.entity_manager', '@App\Service\FileService', '@twig', '@security.token_storage', '@security.authorization_checker','@security.user_password_hasher']
        tags:
            - { name: sonata.admin, code:  ~, model_class: App\Entity\Sale\SaleInvoice, controller: App\Controller\Admin\Sale\SaleInvoiceAdminController, manager_type: orm, label: 'Factura', group: 'Ventas', label_translator_strategy: 'sonata.admin.label.strategy.noop' }
        calls:
            - [ setTemplate, [ edit, 'admin/sale-invoice/edit.html.twig' ] ]
            - [ setTranslationDomain, [ 'admin' ] ]
    app.admin.sale_invoice_due_date:
        class: App\Admin\Sale\SaleInvoiceDueDateAdmin
        arguments: [ '@liip_imagine.cache.manager', '@App\Manager\YearChoicesManager', '@App\Manager\InvoiceManager', '@App\Manager\RepositoriesManager', '@App\Manager\DeliveryNoteManager','@App\Manager\VehicleMaintenanceManager', '@doctrine.orm.entity_manager', '@App\Service\FileService', '@twig', '@security.token_storage', '@security.authorization_checker','@security.user_password_hasher']
        tags:
            - { name: sonata.admin, code:  ~, model_class: App\Entity\Sale\SaleInvoiceDueDate, controller: ~, manager_type: orm, label: 'Vencimientos de venta', group: 'Cartera', label_translator_strategy: 'sonata.admin.label.strategy.noop' }
        calls:
            - [ setTranslationDomain, [ 'admin' ] ]
            - [ setTemplate, [ list, 'admin/due-date/list.html.twig' ] ]
    app.admin.sale_request_has_delivery_note:
        class: App\Admin\Sale\SaleRequestHasDeliveryNoteAdmin
        arguments: [ '@liip_imagine.cache.manager', '@App\Manager\YearChoicesManager', '@App\Manager\InvoiceManager', '@App\Manager\RepositoriesManager', '@App\Manager\DeliveryNoteManager','@App\Manager\VehicleMaintenanceManager', '@doctrine.orm.entity_manager', '@App\Service\FileService', '@twig', '@security.token_storage', '@security.authorization_checker','@security.user_password_hasher']
        tags:
            - { name: sonata.admin, code:  ~, model_class: App\Entity\Sale\SaleRequestHasDeliveryNote, controller: App\Controller\Admin\Sale\SaleRequestHasDeliveryNoteAdminController, manager_type: orm, label: 'Valoración petición-albarán', group: 'Ventas', label_translator_strategy: 'sonata.admin.label.strategy.noop' }
        calls:
            - [ setTranslationDomain, [ 'admin' ] ]
    app.admin.sale_service_tariff:
        class: App\Admin\Sale\SaleServiceTariffAdmin
        arguments: [ '@liip_imagine.cache.manager', '@App\Manager\YearChoicesManager', '@App\Manager\InvoiceManager', '@App\Manager\RepositoriesManager', '@App\Manager\DeliveryNoteManager','@App\Manager\VehicleMaintenanceManager', '@doctrine.orm.entity_manager', '@App\Service\FileService', '@twig', '@security.token_storage', '@security.authorization_checker','@security.user_password_hasher']
        tags:
            - { name: sonata.admin, code:  ~, model_class: App\Entity\Sale\SaleServiceTariff, controller: App\Controller\Admin\Sale\SaleServiceTariffAdminController, manager_type: orm, label: 'Tonelaje', group: 'Ventas', label_translator_strategy: 'sonata.admin.label.strategy.noop' }
        calls:
            - [ setTranslationDomain, [ 'admin' ] ]
    app.admin.sale_item:
        class: App\Admin\Sale\SaleItemAdmin
        arguments: [ '@liip_imagine.cache.manager', '@App\Manager\YearChoicesManager', '@App\Manager\InvoiceManager', '@App\Manager\RepositoriesManager', '@App\Manager\DeliveryNoteManager','@App\Manager\VehicleMaintenanceManager', '@doctrine.orm.entity_manager', '@App\Service\FileService', '@twig', '@security.token_storage', '@security.authorization_checker','@security.user_password_hasher']
        tags:
            - { name: sonata.admin, code:  ~, model_class: App\Entity\Sale\SaleItem, controller: ~, manager_type: orm, label: 'Items', group: 'Ventas', label_translator_strategy: 'sonata.admin.label.strategy.noop' }
        calls:
            - [ setTranslationDomain, [ 'admin' ] ]
    app.admin.sale_request_document:
        class: App\Admin\Sale\SaleRequestDocumentAdmin
        arguments: [ '@liip_imagine.cache.manager', '@App\Manager\YearChoicesManager', '@App\Manager\InvoiceManager', '@App\Manager\RepositoriesManager', '@App\Manager\DeliveryNoteManager','@App\Manager\VehicleMaintenanceManager', '@doctrine.orm.entity_manager', '@App\Service\FileService', '@twig', '@security.token_storage', '@security.authorization_checker','@security.user_password_hasher']
        tags:
            - { name: sonata.admin, code:  ~, model_class: App\Entity\Sale\SaleRequestDocument, controller: App\Controller\Admin\Sale\SaleRequestDocumentAdminController, manager_type: orm, label: 'Documentos de petición', group: 'Ventas', label_translator_strategy: 'sonata.admin.label.strategy.noop' }
        calls:
            - [ setTranslationDomain, [ 'admin' ] ]
