# Sonata Admin
services:
# Vehicle group
    app.admin.vehicle:
        class: App\Admin\Vehicle\VehicleAdmin
        arguments: [ ~ , App\Entity\Vehicle\Vehicle, App\Controller\Admin\Vehicle\VehicleAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.user_password_hasher"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Vehículo", group: "Vehículos", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTemplate, [ edit, "admin/vehicle/edit.html.twig" ] ]
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.vehicle_category:
        class: App\Admin\Vehicle\VehicleCategoryAdmin
        arguments: [ ~ , App\Entity\Vehicle\VehicleCategory, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.user_password_hasher"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Categoría Vehículo", group: "Vehículos", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.vehicle_checking_type:
        class: App\Admin\Vehicle\VehicleCheckingTypeAdmin
        arguments: [ ~, App\Entity\Vehicle\VehicleCheckingType, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.user_password_hasher"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tipo revisión", group: "Vehículos", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.vehicle_checking:
        class: App\Admin\Vehicle\VehicleCheckingAdmin
        arguments: [ ~, App\Entity\Vehicle\VehicleChecking, App\Controller\Admin\Vehicle\VehicleCheckingAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.user_password_hasher"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Revisión", group: "Vehículos", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTemplate, [ list, "admin/vehicle-checking/list.html.twig" ] ]
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.vehicle.digital_tachograph:
        class: App\Admin\Vehicle\VehicleDigitalTachographAdmin
        arguments: [ ~, App\Entity\Vehicle\VehicleDigitalTachograph, App\Controller\Admin\Vehicle\VehicleDigitalTachographAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.user_password_hasher"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Tacógrafo", group: "Vehículos", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.vehicle.consumption:
        class: App\Admin\Vehicle\VehicleConsumptionAdmin
        arguments: [ ~, App\Entity\Vehicle\VehicleConsumption, App\Controller\Admin\Vehicle\VehicleConsumptionAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.user_password_hasher"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Consumos de combustible", group: "Vehículos", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTemplate, [ list, "admin/vehicle-consumption/list.html.twig" ] ]
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.vehicle_fuel:
        class: App\Admin\Vehicle\VehicleFuelAdmin
        arguments: [ ~, App\Entity\Vehicle\VehicleFuel, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.user_password_hasher"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Combustible", group: "Vehículos", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.vehicle.maintenance_task:
        class: App\Admin\Vehicle\VehicleMaintenanceTaskAdmin
        arguments: [ ~, App\Entity\Vehicle\VehicleMaintenanceTask, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.user_password_hasher"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Procesos de taller", group: "Vehículos", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTemplate, [ edit, "admin/vehicle-maintenance-task/edit.html.twig" ] ]
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.vehicle.maintenance:
        class: App\Admin\Vehicle\VehicleMaintenanceAdmin
        arguments: [ ~, App\Entity\Vehicle\VehicleMaintenance, App\Controller\Admin\Vehicle\VehicleMaintenanceAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.user_password_hasher"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Mantenimientos de vehículo", group: "Vehículos", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTemplate, [ list, "admin/vehicle-maintenance/list.html.twig" ] ]
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.vehicle.special_permit:
        class: App\Admin\Vehicle\VehicleSpecialPermitAdmin
        arguments: [ ~, App\Entity\Vehicle\VehicleSpecialPermit, App\Controller\Admin\Vehicle\VehicleSpecialPermitAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.user_password_hasher"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Permisos especiales", group: "Vehículos", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTemplate, [ list, "admin/vehicle-special-permit/list.html.twig" ] ]
            - [ setTranslationDomain, [ "admin" ] ]
