# Web group
services:
    app.admin.service:
        class: App\Admin\Web\ServiceAdmin
        arguments: [ ~ , App\Entity\Web\Service, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.user_password_hasher"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Servicio", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.work:
        class: App\Admin\Web\WorkAdmin
        arguments: [ ~ , App\Entity\Web\Work, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.user_password_hasher"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Trabajo", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.work_image:
        class: App\Admin\Web\WorkImageAdmin
        arguments: [ ~ , App\Entity\Web\WorkImage, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.user_password_hasher"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Imagen Trabajo", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
        calls:
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.complement:
        class: App\Admin\Web\ComplementAdmin
        arguments: [ ~ , App\Entity\Web\Complement, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.user_password_hasher"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Accesorio", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTranslationDomain, [ "admin" ] ]
    app.admin.contact_message:
        class: App\Admin\Web\ContactMessageAdmin
        arguments: [ ~, App\Entity\Web\ContactMessage, App\Controller\Admin\Web\ContactMessageAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager","@app.vehicle_maintenance_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@twig", "@security.token_storage", "@security.authorization_checker","@security.user_password_hasher"]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Mensaje de Contacto", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop" }
        calls:
            - [ setTranslationDomain, [ "admin" ] ]
