# Web group
services:
    app.admin.service:
        class: App\Admin\Web\ServiceAdmin
        arguments: [ ~ , App\Entity\Web\Service, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Servei", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.work:
        class: App\Admin\Web\WorkAdmin
        arguments: [ ~ , App\Entity\Web\Work, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Treball", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.work_image:
        class: App\Admin\Web\WorkImageAdmin
        arguments: [ ~ , App\Entity\Web\WorkImage, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Imatge Treball", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop", show_in_dashboard: false }
    app.admin.complement:
        class: App\Admin\Web\ComplementAdmin
        arguments: [ ~ , App\Entity\Web\Complement, ~, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Accesori", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop" }
    app.admin.contact_message:
        class: App\Admin\Web\ContactMessageAdmin
        arguments: [ ~, App\Entity\Web\ContactMessage, App\Controller\Admin\Web\ContactMessageAdminController, "@liip_imagine.cache.manager", "@app.year_choices_manager", "@app.invoice_manager", "@app.repositories_manager", "@app.delivery_note_manager", "@doctrine.orm.entity_manager", "@app.file_service", "@templating", "@security.token_storage", "@security.authorization_checker" ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: "Missatge de Contacte", group: "Web", label_translator_strategy: "sonata.admin.label.strategy.noop" }
