---
- name: Deploy project to production server
  hosts: s6
  gather_facts: false
  roles:
    - { role: "cbrunnkvist.ansistrano-symfony-deploy" }
  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  vars:
    # ansistrano deploys config
    ansistrano_deploy_from: "{{ playbook_dir }}/../../"
    ansistrano_deploy_to: "{{ vhost_path }}"
    ansistrano_keep_releases: 3
    # ansistrano shared resources
    ansistrano_shared_paths:
      - "var/log"
      - "public/uploads"
      - "public/pdfs"
    ansistrano_shared_files: []
    ansistrano_ensure_shared_paths_exist: yes
    ansistrano_ensure_basedirs_shared_files_exist: yes
    # ansistrano repository config
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: "{{ vhost_git_clone_repo }}"
    ansistrano_git_branch: "master"
    # ansistrano hooks
    ansistrano_before_symlink_tasks_file: "{{ playbook_dir }}/hooks/before-symlink-tasks.yml"
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/hooks/after-symlink-tasks.yml"
    ansistrano_after_cleanup_tasks_file: "{{ playbook_dir }}/hooks/after-cleanup-tasks.yml"
    ansistrano_before_symlink_shared_tasks_file: "{{ playbook_dir }}/hooks/before-symlink-shared-tasks.yml"
    # symfony config
    symfony_console_path: "bin/console"
    symfony_run_composer: true
    symfony_composer_path: "{{ ansistrano_deploy_to }}/composer.phar"
    symfony_composer_options: "--no-dev --optimize-autoloader --no-interaction --no-plugins --no-scripts"
    symfony_composer_self_update: false
    symfony_run_assets_install: true
    symfony_run_assetic_dump: false
    symfony_run_cache_clear_and_warmup: true
    symfony_run_doctrine_migrations: true
