---
- hosts: s6
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/vars/config.yml"
  tasks:
    - name: execute province CSV import by partner primary address to local database
      delegate_to: mother
      shell: "php app/console app:import:province app/csv/partners.csv 9 10"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute province CSV import by partner secondary address to local database
      delegate_to: mother
      shell: "php app/console app:import:province app/csv/partners.csv 19 20"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute province CSV import by enterprise to local database
      delegate_to: mother
      shell: "php app/console app:import:province app/csv/enterprises.csv 5 6"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute province CSV import by operator to local database
      delegate_to: mother
      shell: "php app/console app:import:province app/csv/operators.csv 12 12"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute city CSV import by partner primary address to local database
      delegate_to: mother
      shell: "php app/console app:import:city app/csv/partners.csv 8 6 9 10"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute city CSV import by partner secondary address to local database
      delegate_to: mother
      shell: "php app/console app:import:city app/csv/partners.csv 18 17 19 20"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute city CSV import by enterprise to local database
      delegate_to: mother
      shell: "php app/console app:import:city app/csv/enterprises.csv 4 7 5 6"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute city CSV import by operator to local database
      delegate_to: mother
      shell: "php app/console app:import:city app/csv/operators.csv 11 10 12 12"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute enterprise CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:enterprise app/csv/enterprises.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute enterprise activity lines CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:enterprise:activity:line app/csv/enterprise_activity_lines.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute enterprise collection document types CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:enterprise:collection:document:type app/csv/enterprise_collection_document_types.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute enterprise group bountys CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:enterprise:group:bounty app/csv/enterprise_group_bountys.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute enterprise holidays CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:enterprise:holiday app/csv/enterprise_holidays.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute enterprise transfer accounts CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:enterprise:transfer:account app/csv/enterprise_transfer_accounts.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute operator CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:operator app/csv/operators.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute operator checking type CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:operator:checking:type app/csv/operator_checking_types.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute operator checking CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:operator:checking app/csv/operator_checkings.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute operator absence type CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:operator:absence:type app/csv/operator_absence_types.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute operator absence CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:operator:absence app/csv/operator_absences.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute operator digital tachographs CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:operator:digital:tachograph app/csv/operator_digital_tachographs.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute operator various amount CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:operator:various:amount app/csv/operator_various_amounts.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute partner class CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:partner:class app/csv/partner_classes.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute partner type CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:partner:type app/csv/partner_types.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute partner CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:partner app/csv/partners.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute partner contact CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:partner:contact app/csv/partner_contacts.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute partner unable days CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:partner:unable:days app/csv/partner_unabled_days.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute partner building site CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:partner:building:site app/csv/partner_building_sites.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute partner order CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:partner:order app/csv/partner_orders.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute setting sale invoice series CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:setting:sale:invoice:series app/csv/setting_sale_invoice_series.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute sale tariff CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:sale:tariff app/csv/sale_tariff.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
    - name: execute sale invoice CSV import to local database
      delegate_to: mother
      shell: "php app/console app:import:sale:invoice app/csv/sale_invoice.csv"
      args:
        chdir: "{{ playbook_dir}}/../../"
