- name: copy .env production file
  copy:
    src: "{{ playbook_dir }}/vars/.env.prod"
    dest: "{{ ansistrano_release_path.stdout }}/.env"
- name: copy composer auth file
  copy:
    src: "{{ playbook_dir }}/vars/auth.json"
    dest: "{{ ansistrano_release_path.stdout }}/auth.json"